import { NextResponse } from 'next/server'

export async function GET() {
  const folds = [],
        initialHeight = 0.1,
        descs = [
          "You have a piece of paper.",
          "The thickness of a strand of human hair",
          "The width of a grain of sand",
          "The width of a pencil's tip",
          "The thickness of a strand of spaghetti",
          "The height of a ladybug",
          "The thickness of a sunflower seed",
          "The length of a coffee bean",
          "The width of a penny",
          "The height of a chicken egg",
          "The height of a hummingbird",
          "The height of a basketball",
          "The height of a bowling pin",
          "The height of a cheetah",
          "The height of an average woman",
          "The length of a Volkswagen Beetle",
          "The height of a giraffe",
          "About the height of an oak tree",
          "The length of a blue whale",
          "The wingspan of a Boeing 747",
          "About the height of the Statue of Liberty",
          "About the height of the Gateway Arch",
          "Taller than the Eiffel Tower",
          "As tall as the Burj Khalifa",
          "The length of the Kentucky Derby",
          "The length of Central Park",
          "The length of the Las Vegas Strip",
          "Taller than Mount Everest",
          "Deeper than the Mariana Trench",
          "About the length of Rhode Island",
          "The alititude at which space begins",
          "Longer than the Suez Canal",
          "As long as the Grand Canyon",
          "500 laps around Indianapolis Motor Speedway",
          "Longer than California",
          "Longer than the diameter of Pluto",
          "About the diameter of Mars",
          "The distance from New York to Sydney",
          "Tall enough to wrap around the Earth",
          "Longer than the diameter of Neptune",
          "The diameter of Saturn without its rings",
          "The diameter of Proxima Centauri, a red star",
          "Congratulations, after only 42 folds your piece of paper has reached the moon!"
        ],
        imgs = [
          '00-paper.png',
          '01-hair.jpg',
          '02-sand.jpg',
          '03-pencil.jpg',
          '04-spaghetti.jpg',
          '05-ladybug.jpg',
          '06-sunflower-seed.jpg',
          '07-coffee-bean.jpg',
          '08-penny.jpg',
          '09-chicken-egg.jpg',
          '10-hummingbird.jpg',
          '11-basketball.jpg',
          '12-bowling-pin.jpg',
          '13-cheetah.jpg',
          '14-woman.jpg',
          '15-volkswagen-beetle.webp',
          '16-giraffe.jpg',
          '17-oak-tree.jpg',
          '18-blue-whale.jpg',
          '19-boeing-747.webp',
          '20-statue-of-liberty.webp',
          '21-gateway-arch.jpg',
          '22-eiffel-tower.jpg',
          '23-burj-khalifa.jpg',
          '24-kentucky-derby.jpg',
          '25-central-park.jpg',
          '26-las-vegas-strip.jpg',
          '27-mount-everest.webp',
          '28-mariana-trench.webp',
          '29-rhode-island.jpg',
          '30-outer-space.webp',
          '31-suez-canal.jpg',
          '32-the-grand-canyon.webp',
          '33-indianapolis-motor-speedway.jpg',
          '34-california.webp',
          '35-pluto.jpg',
          '36-mars.png',
          '37-new-york-to-sydney.png',
          '38-earth.jpg',
          '39-neptune.webp',
          '40-saturn.jpg',
          '41-proxima-centauri.webp',
          '42-earth-to-moon.png'
        ]
  for (let i = 0; i <= 42; i++) {
    const el = {
      id: i + 1,
      folds: i,
      height: initialHeight * (2 ** i),
      desc: descs[i],
      imgPath: imgs[i]
    }
    folds.push(el)
  }
  return NextResponse.json({folds})
}
